import { PUSH_NOTIFICATION, POP_NOTIFICATION, INITIAL_STATE_NOTIFICATION } from './notification'

export default {
  notification: {
    INITIAL_STATE_NOTIFICATION,
    PUSH_NOTIFICATION,
    POP_NOTIFICATION
  }
}
